#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <unordered_set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
#include <iomanip>
#include <regex>
#include <atcoder/all>
using namespace std;
using namespace atcoder;

#define REP(i, n) for (int i = 0, i##_len = (n); i < i##_len; ++i)
#define FOR(i, a, b) for (int i = (a), i##_len = (b); i <= i##_len; ++i)
#define REV(i, a, b) for (int i = (a); i >= (b); --i)
#define CLR(a, b) memset((a), (b), sizeof(a))
#define DUMP(x) cout << #x << " = " << (x) << endl;
#define INF_ll 1001001001001001001ll
#define INF 1001001001
#define fcout cout << fixed << setprecision(12)

using ll = long long;
using vi = vector<int>;
using vl = vector<long long>;
using vs = vector<string>;
using vc = vector<char>;
using vb = vector<bool>;
using vpii = vector<pair<int, int>>;
using vpll = vector<pair<long long, long long>>;
using vvi = vector<vector<int>>;
using vvl = vector<vector<long long>>;
using vvc = vector<vector<char>>;
using vvb = vector<vector<bool>>;
using vvvi = vector<vector<vector<int>>>;
using pii = pair<int, int>;

template <typename T>
inline bool chmax(T &a, T b) {
    return ((a < b) ? (a = b, true) : (false));
}
template <typename T>
inline bool chmin(T &a, T b) {
    return ((a > b) ? (a = b, true) : (false));
}

const string YES = "Yes";
const string NO = "No";

void solve(long long N, std::vector<long long> A, long long M, std::vector<long long> B, long long L, std::vector<long long> C, long long Q, std::vector<long long> X){
    unordered_set<int> st;
    REP(i, N) REP(j, M) REP(k, L) {
        st.insert(A.at(i) + B.at(j) + C.at(k));
    }
    REP(qi, Q) {
        cout <<  ((st.count(X.at(qi))) ? YES : NO) << "\n";
    }
    return;
}

// Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
        long long N;
    std::scanf("%lld", &N);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        std::scanf("%lld", &A[i]);
    }
    long long M;
    std::scanf("%lld", &M);
    std::vector<long long> B(M);
    for(int i = 0 ; i < M ; i++){
        std::scanf("%lld", &B[i]);
    }
    long long L;
    std::scanf("%lld", &L);
    std::vector<long long> C(L);
    for(int i = 0 ; i < L ; i++){
        std::scanf("%lld", &C[i]);
    }
    long long Q;
    std::scanf("%lld", &Q);
    std::vector<long long> X(Q);
    for(int i = 0 ; i < Q ; i++){
        std::scanf("%lld", &X[i]);
    }
        solve(N, std::move(A), M, std::move(B), L, std::move(C), Q, std::move(X));
        return 0;
}
